name: AppName

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    restart: unless-stopped

  
  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgres/data:/var/lib/postgresql
    ports:
      - 5433:5432/tcp
 